# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: targetBoard
    type: string
  - name: targetSeries
    type: string
  - name: needsDFU
    type: boolean
    default: false
  - name: buildOptions
    type: string
    default: ''

jobs:
- job: Build_${{ parameters.targetBoard }}
  condition: >-
    or(
      contains(stageDependencies.Check_Build_Options.Check_Build_Options.outputs['BuildOptions.COMMIT_MESSAGE_FROMPR'], '[x] ${{ parameters.targetBoard }}'),
      contains(stageDependencies.Check_Build_Options.Check_Build_Options.outputs['BuildOptions.COMMIT_MESSAGE_FROMPR'], '[x] BUILD ALL'),
      eq(variables['BUILD_ALL'], 'true'),
      eq(variables['BUILD_${{ parameters.targetBoard }}'], 'true'),
      eq(stageDependencies.Check_Build_Options.Check_Build_Options.outputs['BuildOptions.GO'], 'True')
    )

  pool:
    vmImage: 'windows-latest'

  variables:
    TargetBoard: ${{ parameters.targetBoard }}
    TargetPlatform: 'stm32'
    TargetSeries: ${{ parameters.targetSeries }}
    BuildOptions: ${{ parameters.buildOptions }}
    REVISION: $[counter('${{ parameters.targetBoard }}_versioncounter_1_17_0', 0)]
    GccArm_Version:
    NeedsDFU: ${{ parameters.needsDFU }}
    NeedsSRECORD: false
    CMakePreset: ${{ parameters.targetBoard }}

  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: templatesBuild
    fetchDepth: 1

  - template: clone-nf-interpreter-repo.yml
  - template: azure-pipelines-templates/build-preparations.yml@templatesBuild
    parameters:
      repoDirectory: '$(Build.SourcesDirectory)\nf-interpreter'
  - template: azure-pipelines-templates/nb-gitversioning.yml@templatesBuild
    parameters:
      repoDirectory: '$(Build.SourcesDirectory)\nf-interpreter'
  - template: azure-pipelines-templates/download-install-arm-gcc-toolchain.yml@templatesBuild
  - template: azure-pipelines-templates/download-hexdfu.yml@templatesBuild
  - template: azure-pipelines-templates/install-kconfig-tools.yml@templatesBuild
    parameters:
      repoDirectory: '$(Build.SourcesDirectory)\nf-interpreter'
  - template: azure-pipelines-templates/build-chibios-stm32-targets.yml@templatesBuild
    parameters:
      repoDirectory: $(Build.SourcesDirectory)\nf-interpreter
  - template: azure-pipelines-templates/pack-publish-artifacts.yml@templatesBuild
    parameters:
      buildDirectory: $(Build.SourcesDirectory)\nf-interpreter\build
  - template: azure-pipelines-templates/publish-cloudsmith.yml@templatesBuild
