#ifndef _SMARTRF_SETTINGS_PREDEFINED_H_
#define _SMARTRF_SETTINGS_PREDEFINED_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.14.0 (build #182)
// Tested for SimpleLink SDK version: CC13x2 SDK 2.30.xx.xx or newer
// Device: CC1352P Rev. E (2.1)
//
//*********************************************************************************


#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define RF_PROP_TX_POWER_TABLE_SIZE 26

// TX Power Table Object
extern RF_TxPowerTable_Entry RF_PROP_txPowerTable[];

/* RF Core API commands */
/* RF command pointers for easylink */
extern RF_Mode RF_prop_fsk;
extern RF_Mode RF_prop_sl_lr;
extern RF_Mode RF_prop_fsk_200kbps;

extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_cmdPropRadioDivSetup_fsk;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_cmdPropRadioDivSetup_sl_lr;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_cmdPropRadioDivSetup_fsk_200kbps;

extern rfc_CMD_FS_t RF_cmdFs_preDef;
extern rfc_CMD_PROP_TX_ADV_t RF_cmdPropTxAdv_preDef;
extern rfc_CMD_PROP_RX_ADV_t RF_cmdPropRxAdv_preDef;

extern uint32_t pOverrides_fsk[];
extern uint32_t pOverrides_sl_lr[];
extern uint32_t pOverrides_fsk_200kbps[];
extern uint32_t pOverridesTxStd_sub1[];
extern uint32_t pOverridesTx20_sub1[];


#endif // _SMARTRF_SETTINGS_PREDEFINED_H_
